name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run backend and frontend with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 10

      - name: Test backend is working
        run: |
          curl -f http://localhost:5000 || exit 1

      - name: Test frontend is working
        run: |
          curl -f http://localhost:3000 || exit 1

      - name: Stop services
        run: docker-compose down
