name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run backend and frontend with Docker Compose
        run: |
          docker-compose up -d --build
          sleep 10  # Wait for services to be ready

      - name: Test backend is working
        run: |
          curl -f http://localhost:5000 || exit 1

      - name: Test frontend is working
        run: |
          curl -f http://localhost:3000 || exit 1

      - name: Stop services
        run: docker-compose down
