name: Fullstack CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          docker build -t my-backend ./backend
          docker build -t my-frontend ./frontend

      - name: Run tests (optional)
        run: echo "Add unit tests here"

      - name: Deploy step (optional)
        run: echo "Deploy to cloud/Kubernetes here"
